<a href="https://colab.research.google.com/github/bindumadamanchi3/ai-upskilling-journey/blob/main/NumPy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(type(arr))

print(arr.shape)
print(arr.size)

reshaped = arr.reshape(3,2)
print(reshaped)
print(reshaped.shape)


<class 'numpy.ndarray'>
(2, 3)
6
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [ ]:
#check number of dimensions

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

print(d)


0
1
2
3
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
from numpy import random

x = random.choice([2,3], p=[0.5,0.5], size=(10))

print(x)


[2 2 3 3 2 3 2 2 2 3]


In [ ]:
import numpy as np

# 1a. Create a 1D array of numbers 1 to 10
# 1b. Create a 3x3 matrix of all zeros (float)
# 1c. Create a 3x3 identity matrix
# 1d. Create an array of 5 evenly spaced values between 0 and 1
# 1e. Create a 2x4 array filled with the value 7

arr_1d = np.arange(1,11)
print(arr_1d)

arr_3d = np.zeros((3,3))
print(arr_3d)

identity_matrix = np.eye(3)
print(identity_matrix)

even_spaced_values = np.linspace(0,1,5)
print(even_spaced_values)

fill_same_value = np.full((2,4),7)
print(fill_same_value)

[ 1  2  3  4  5  6  7  8  9 10]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.   0.25 0.5  0.75 1.  ]
[[7 7 7 7]
 [7 7 7 7]]


In [ ]:
# Given this flat array, reshape it into a 3x4 matrix
# Then print its shape, number of dimensions, total elements, and dtype
# Expected shape: (3, 4), ndim: 2, size: 12, dtype: int64
import numpy as np

arr = np.arange(12)

new_arr = arr.reshape((3,4))
print(new_arr)

print(new_arr.shape)
print(new_arr.ndim)
print(new_arr.size)
print(new_arr.dtype)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2
12
int64
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
#random arrays and seeding
# Create:
# 3a. A 4x4 random float matrix (values 0-1)
# 3b. A 1D array of 6 random integers between 1 and 100
# 3c. Repeat 3b but ensure the same result every time (reproducible)

import numpy as np

a = np.random.rand(4, 4)
np.random.seed(42)
b = np.random.randint(1, 101, size=6)
np.random.seed(42)
c = np.random.randint(1, 101, size=6)

print(a)
print(b)
print(c)

[[0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502 0.29122914]]
[52 93 15 72 61 21]
[52 93 15 72 61 21]


In [3]:
#stack and concatenate arrays
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 4a. Stack horizontally → [1 2 3 4 5 6]
print(np.hstack([a,b]))

# 4b. Stack vertically → [[1 2 3], [4 5 6]]
print(np.vstack([a,b]))

# 4c. Stack as columns → [[1 4], [2 5], [3 6]]
print(np.column_stack([a,b]))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [7]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([2, 4, 5, 8, 10])

# Compute: a+b, a-b, a*b, a/b, a**2, a % 3
# No loops allowed.
total = a + b
print(total)

diff = a - b
print(diff)

multiply = a * b
print(multiply)

divide = a / b
print(divide)

square = a ** 2
print(square)

percentile = a % 3
print(percentile)

[12 24 35 48 60]
[ 8 16 25 32 40]
[ 20  80 150 320 500]
[5. 5. 6. 5. 5.]
[ 100  400  900 1600 2500]
[1 2 0 1 2]


In [13]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Compute:
# 6a. Sum of entire matrix
# 6b. Sum of each column (axis=0)
# 6c. Sum of each row (axis=1)
# 6d. Mean, max, min of entire matrix
# 6e. Which row has the highest sum?

print(matrix.sum())
print(matrix.sum(axis=0))
print(matrix.sum(axis=1))
print(matrix.mean())
print(matrix.max())
print(matrix.min())
print(np.argmax(matrix.sum(axis=1)))

45
[12 15 18]
[ 6 15 24]
5.0
9
1
2


In [20]:
# 7a. Add a different value to each column of a 3x3 matrix
#     without writing a loop. Add [10, 20, 30] to each row.
#
# 7b. Normalise each row of the matrix so values are between 0 and 1
#     (subtract row min, divide by row range)

matrix = np.array([
    [1, 2, 3],
    [4, 8, 12],
    [5, 10, 15]
])

a = matrix + np.array([10, 20, 30])
print(a)

row_min = matrix.min(axis=1, keepdims=True)    # shape (3,1)
row_max = matrix.max(axis=1, keepdims=True)    # shape (3,1)
print(row_min)
print(row_max)

normalized_matrix = (matrix-row_min)/(row_max-row_min)
print(normalized_matrix)

[[11 22 33]
 [14 28 42]
 [15 30 45]]
[[1]
 [4]
 [5]]
[[ 3]
 [12]
 [15]]
[[0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]]


In [24]:
# 8a. Multiply two 3x3 matrices (true matrix multiplication, not element-wise)
# 8b. Compute dot product of two 1D vectors
# 8c. Multiply a (3,4) matrix by a (4,2) matrix and check the output shape

A = np.random.randint(1, 5, size=(3, 3))
B = np.random.randint(1, 5, size=(3, 3))
a = A @ B
print(a)
print(a.shape)

C = np.array([1,2,3])
D = np.array([4,5,6])
b = np.dot(C, D)
print(b)

X = np.ones((3, 4))
Y = np.ones((4, 2))
c = X @ Y
print(c)
print(c.shape)

[[29 25 40]
 [30 26 40]
 [26 24 36]]
(3, 3)
32
[[4. 4.]
 [4. 4.]
 [4. 4.]]
(3, 2)


In [27]:
#Indexing 1D array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Extract:
# 9a. First 3 elements
print(arr[:3])

# 9b. Last 3 elements
print(arr[-3:])

# 9c. Every other element
print(arr[::2])

# 9d. Elements from index 3 to 7
print(arr[3:8])

# 9e. Reversed array
print(arr[::-1])



[10 20 30]
[ 80  90 100]
[10 30 50 70 90]
[40 50 60 70 80]
[100  90  80  70  60  50  40  30  20  10]


In [37]:
#Indexing 2D array
matrix = np.arange(1, 26).reshape(5, 5)
# [[ 1  2  3  4  5]
#  [ 6  7  8  9 10]
#  [11 12 13 14 15]
#  [16 17 18 19 20]
#  [21 22 23 24 25]]

# Extract:
# 10a. Element at row 2, col 3 (value 14)
print(matrix[1,2])

# 10b. Entire third row
print(matrix[2])

# 10c. Entire second column
print(matrix[:,1])

# 10d. Top-left 2x2 submatrix
print(matrix[0:2, 0:2]) #just :2 will also work

# 10e. Bottom-right 3x3 submatrix
print(matrix[-3:, -3:])
print(matrix[2:, 2:]) #pythonic way until unless the above one is specifically mentioned


8
[11 12 13 14 15]
[ 2  7 12 17 22]
[[1 2]
 [6 7]]
[[13 14 15]
 [18 19 20]
 [23 24 25]]
[[13 14 15]
 [18 19 20]
 [23 24 25]]


In [3]:
#Boolean indexing
import numpy as np

scores = np.array([45, 82, 91, 37, 68, 55, 77, 94, 29, 61])

# 11a. Extract all scores above 70
print(scores > 70)  #[False  True  True False False False  True  True False False]
print(scores[scores > 70])

# 11b. Set all scores below 50 to 0
result = scores.copy() #creates a new array and the original stays unchanged
result[result < 50] = 0
print(result)

# 11c. Count how many scores are between 60 and 80 (inclusive)
a = (scores > 60) & (scores < 80)

print(scores[a].size)
     #OR
print(a.sum()) # sum of 1's

# 11d. Replace scores above 90 with exactly 90 (cap/clip)
capped = np.clip(scores, 0, 90)
print(capped)

[False  True  True False False False  True  True False False]
[82 91 77 94]
[ 0 82 91  0 68 55 77 94  0 61]
10
3
[45 82 90 37 68 55 77 90 29 61]
