<a href="https://colab.research.google.com/github/bindumadamanchi3/ai-upskilling-journey/blob/main/NumPy_%2B_Math_Intution_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# We'll use these arrays throughout all exercises
scores     = np.array([72, 85, 90, 61, 78, 95, 88, 73, 82, 79])
costs      = np.array([0.013, 0.019, 0.0, 0.015, 0.005, 0.046, 0.005, 0.008, 0.0, 0.012])
latencies  = np.array([420, 890, 5100, 760, 210, 1100, 340, 280, 6200, 650])
embeddings = np.random.seed(42) or np.random.randn(5, 4)   # 5 tokens, 4-dim vectors

print(scores)
print(costs)
print(latencies)
print(embeddings)

[72 85 90 61 78 95 88 73 82 79]
[0.013 0.019 0.    0.015 0.005 0.046 0.005 0.008 0.    0.012]
[ 420  890 5100  760  210 1100  340  280 6200  650]
[[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783 -0.56228753]
 [-1.01283112  0.31424733 -0.90802408 -1.4123037 ]]


In [ ]:
#Basic mean (Easy)
#Compute the mean of the eval scores array. Then compute the mean of only the scores above 80. Compare the two.
scores = np.array([72, 85, 90, 61, 78, 95, 88, 73, 82, 79])

# 1a. Mean of all scores
a = np.mean(scores)
print(a)

# 1b. Mean of scores above 80 only
b = np.mean(scores[scores > 80])
print(b)

# 1c. How much higher is the filtered mean vs overall mean?
print(round((b-a), 2))


80.3
88.0
7.7


In [ ]:
# Axis-wise mean on a 2D array (Easy)
#You have a matrix where each row is a model and each column is an eval run score. Compute the mean score per model (row mean) and the mean score per eval run (column mean).
model_scores = np.array([
    [82, 79, 85, 88],   # GPT-4
    [74, 80, 76, 83],   # Claude
    [91, 88, 94, 90],   # Gemini
])

# 2a. Mean score per model (one value per row)
row_means = model_scores.mean(axis=1)
print(f"Mean per eval run: {row_means}")

# 2b. Mean score per eval run (one value per column)
col_means = model_scores.mean(axis=0)
print(f"Mean per eval run: {col_means}")

# 2c. Which model performed best on average?
models = ['GPT-4', 'Claude', 'Gemini']
best = models[np.argmax(row_means)]
print(f"Best model: {best}")

Mean per eval run: [83.5  78.25 90.75]
Mean per eval run: [82.33333333 82.33333333 85.         87.        ]
Best model: Gemini


In [ ]:
#Weighted mean (Medium)
#In an LLM eval, not all test cases are equally important. Compute a weighted mean score where harder questions count more.
scores  = np.array([90, 75, 60, 85, 70])
weights = np.array([1,   2,  3,  2,  1])   # harder questions weighted higher

# Weighted mean = sum(score * weight) / sum(weights)
# Expected: ~73.33
result = np.sum(scores * weights) / np.sum(weights)
print(f"weighted mean: {result:.2f}")

#Method 2 - np.average()
weighted_mean = np.average(scores, weights = weights)
print(f"weighted mean using np.average function: {weighted_mean:.2f}")

weighted mean: 73.33
weighted mean using np.average function: 73.33


In [ ]:
#Rolling mean (Mean over a window) (Medium)
#Compute a 3-point rolling mean of the latency array — each value is the mean of itself and the two values before it. This smooths out spikes.
import numpy as np
import pandas as pd

latencies = np.array([420, 890, 5100, 760, 210, 1100, 340, 280, 6200, 650])

s = pd.Series(latencies)
print(s.rolling(window = 3).mean().round(2).values) #This will keep NaN's as it is in the result
#Calculates the mean using 1 point for the first row, 2 points for the second row
print(s.rolling(window=3, min_periods=1).mean().round(2).values) #min_periods=1 - This will not give NaN's from the array to be used for machine learning model or database which cannot accept missing data
# Rolling mean window=3:
# index 0: can't compute (not enough history) → NaN
# index 1: can't compute → NaN
# index 2: mean(420, 890, 5100) = 2136.67
# index 3: mean(890, 5100, 760) = 2250.0
# ... and so on



[    nan     nan 2136.67 2250.   2023.33  690.    550.    573.33 2273.33
 2376.67]
[ 420.    655.   2136.67 2250.   2023.33  690.    550.    573.33 2273.33
 2376.67]


In [ ]:
#Compute variance and std dev (Easy)
#Compute the variance and standard deviation of the eval scores. Then interpret what they tell you about model consistency.
import numpy as np

scores = np.array([72, 85, 90, 61, 78, 95, 88, 73, 82, 79])

# 5a. Population variance and std dev (ddof=0)
pop_var = np.var(scores, ddof=0)
pop_std = np.std(scores, ddof=0)
print(f"Population variance is {pop_var:.2f} and population standard deviation is {pop_std:.2f}")

# 5b. Sample variance and std dev (ddof=1)
sam_var = np.var(scores, ddof=1)
sam_std = np.std(scores, ddof=1)
print(f"Sample variance is {sam_var:.2f} and sample standard deviation is {sam_std:.2f}")

# 5c. What does a std dev of ~10 mean in plain English?
regular_mean = scores.mean()
print(f"Mean is {regular_mean:.2f}")
print(f"Most scores fall between {regular_mean - sam_std:.1f} and {regular_mean + sam_std:.1f}")


Population variance is 89.61 and population standard deviation is 9.47
Sample variance is 99.57 and sample standard deviation is 9.98
Mean is 80.30
Most scores fall between 70.3 and 90.3


In [ ]:
#Compare variance across models (Medium)
# Two models are evaluated 6 times each. Compare their consistency using std dev.
import numpy as np

model_a = np.array([82, 84, 81, 83, 82, 85])   # consistent?
model_b = np.array([70, 95, 78, 91, 65, 88])   # consistent?

# 6a. Compute mean and std dev for both
mean_a, std_a = model_a.mean(), np.std(model_a, ddof=1)
mean_b, std_b = model_b.mean(), np.std(model_b, ddof=1)
print(f"Mean and std for Model A is {mean_a:.2f} and {std_a:.2f}")
print(f"Mean and std for Model B is {mean_b:.2f} and {std_b:.2f}")

# 6b. Which model is more consistent?
consistent_model = "Model A" if std_a < std_b else "Model B"
print(f"More consistent model is: {consistent_model}")

# 6c. Which would you prefer to deploy and why?
print("\nDeploy Model A:")
print(f"  Similar mean ({mean_a:.1f} vs {mean_b:.1f})")
print(f"  But 8x more consistent (std {std_a:.1f} vs {std_b:.1f})")
print(f"  Model B's range: [{model_b.min()}, {model_b.max()}]")
print(f"  Model A's range: [{model_a.min()}, {model_a.max()}]")

Mean and std for Model A is 82.83 and 1.47
Mean and std for Model B is 81.17 and 12.09
More consistent model is: Model A


In [ ]:
# Normalisation using mean and std (Z-score) (Medium)

latencies = np.array([420, 890, 5100, 760, 210, 1100, 340, 280, 6200, 650])

mean = latencies.mean()
std  = latencies.std(ddof=1)

z_scores = (latencies - mean) / std

print(f"Original mean: {mean:.1f}, std: {std:.1f}")
print(f"Normalised mean: {z_scores.mean():.6f}, std: {z_scores.std(ddof=1):.6f}")
# Normalised — mean: 0.000000, std: 1.000000

print(f"\nZ-scores: {np.round(z_scores, 2)}")
# Negative = faster than average, Positive = slower than average
# Large positive values (timeout calls) stand out clearly as outliers

Original  — mean: 1595.0, std: 2171.2
Normalised — mean: -0.000000, std: 1.000000

Z-scores: [-0.54 -0.32  1.61 -0.38 -0.64 -0.23 -0.58 -0.61  2.12 -0.44]


In [ ]:
# Coefficient of Variation (Hard)
# The Coefficient of Variation (CV) is std / mean * 100 — it expresses variability as a percentage of the mean. This lets you compare variability across datasets with different scales.
# Compare the CV of latencies vs costs to find out which is more variable relative to its scale.

import numpy as np

latencies = np.array([420, 890, 5100, 760, 210, 1100, 340, 280, 6200, 650])
costs     = np.array([0.013, 0.019, 0.0, 0.015, 0.005, 0.046, 0.005, 0.008, 0.0, 0.012])

# CV = (std / mean) * 100
# Which is more variable — latency or costs
std_latencies = latencies.std(ddof=1)
std_costs = costs.std(ddof=1)

cv_latencies = std_latencies / latencies.mean() * 100
cv_costs = std_costs / costs.mean() * 100

print(f"Latencies - Mean: {latencies.mean():.2f}, std: {std_latencies:.2f}, CV: {cv_latencies:.2f}")
print(f"Costs - Mean: {costs.mean():.2f}, std: {std_costs:.2f}, CV: {cv_costs:.2f}")
print(f"More Variable: {"Latency" if cv_latencies > cv_costs else "Costs"}")

Latencies - Mean: 1595.00, std: 2171.19, CV: 136.12
Costs - Mean: 0.01, std: 0.01, CV: 108.95
More Variable: Latency


In [ ]:
# Element-wise operations (Easy)
#Given prompt tokens and completion tokens arrays, compute total tokens, cost per call (at $0.00003 per token), and flag calls that exceeded 500 total tokens.

prompt_tokens     = np.array([250, 800, 120, 600, 300, 950, 200, 450, 1200, 500])
completion_tokens = np.array([180, 450,   0, 380, 200, 600, 150, 300,    0, 320])
rate_per_token    = 0.00003

# 9a. Total tokens per call
total_tokens = prompt_tokens + completion_tokens
print(total_tokens)

# 9b. Cost per call
call_cost = (total_tokens * rate_per_token).round(4)
print(f"Calls cost: {call_cost}")

# 9c. Boolean array — True where total tokens > 500
exceeded_500 = total_tokens > 500
print(f"Boolean array for calls that exceeded 500 tokens: {exceeded_500}")


# 9d. How many calls exceeded 500 tokens?
print(f"Number of calls that exceeded 500 tokens: {exceeded_500.sum()}")


[ 430 1250  120  980  500 1550  350  750 1200  820]
Calls cost: [0.0129 0.0375 0.0036 0.0294 0.015  0.0465 0.0105 0.0225 0.036  0.0246]
Boolean array for calls that exceeded 500 tokens: [False  True False  True False  True False  True  True  True]
Number of calls that exceeded 500 tokens: 6


In [ ]:
#Broadcasting (Medium)
# You have a 4x3 matrix of model evaluation scores across 3 tasks. Normalise each row so values fall between 0 and 1 (min-max normalisation per model).
#normalised = (score - row_min) / (row_max - row_min)
import numpy as np

scores = np.array([
    [60, 80, 90],    # Model A across 3 tasks
    [50, 95, 70],    # Model B
    [85, 85, 85],    # Model C
    [40, 60, 100],   # Model D
])

row_min = scores.min(axis = 1, keepdims=True) #keepdims=True is critical — without it, row_min has shape (4,) instead of (4,1) and broadcasting fails.
row_max = scores.max(axis = 1, keepdims=True)

normalized_array = (scores - row_min) / (row_max - row_min)
print(np.round(normalized_array, 2))

# Handle Model C (all same scores — division by zero → nan)
normalised = np.nan_to_num(normalized_array, nan=0.0)  #nan_to_num catches the 0/0 case where all scores are identical.
print(np.round(normalised, 2))


[[0.   0.67 1.  ]
 [0.   1.   0.44]
 [ nan  nan  nan]
 [0.   0.33 1.  ]]
[[0.   0.67 1.  ]
 [0.   1.   0.44]
 [0.   0.   0.  ]
 [0.   0.33 1.  ]]


/tmp/ipykernel_7416/1876616565.py:16: RuntimeWarning: invalid value encountered in divide
  normalized_array = (scores - row_min) / (row_max - row_min)


In [ ]:
#Dot product and cosine similarity (Medium)
#Compute the dot product between two embedding vectors. Then compute the cosine similarity between them. Cosine similarity = dot product of unit vectors.
vec_a = np.array([0.2, 0.8, 0.4, 0.6])   # embedding for "machine learning"
vec_b = np.array([0.3, 0.7, 0.5, 0.5])   # embedding for "deep learning"
vec_c = np.array([0.9, 0.1, 0.1, 0.2])   # embedding for "cooking recipes"

# 11a. Dot product of vec_a and vec_b
print(np.dot(vec_a, vec_b).round(4))

# Cosine similarity between vec_a and vec_b, vec_a and vec_c
def cosine_sim(x, y):
    return np.dot(x, y) / (np.linalg.norm(x) * np.linalg.norm(y))

sim_ab = cosine_sim(vec_a, vec_b)
sim_ac = cosine_sim(vec_a, vec_c)

print(f"Cosine sim a vs b: {sim_ab:.4f}")   # ~0.98 — very similar
print(f"Cosine sim a vs c: {sim_ac:.4f}")   # ~0.41 — less similar

# 11d
more_similar = 'vec_b' if sim_ab > sim_ac else 'vec_c'
print(f"More similar to vec_a: {more_similar}")   # vec_b

1.12
Cosine sim a vs b: 0.9838
Cosine sim a vs c: 0.4111
More similar to vec_a: vec_b


In [ ]:
#Sorting and argsort (Medium)
#You have similarity scores between a query and 8 documents. Find the top 3 most relevant documents using argsort.
doc_ids    = np.array(['doc_0', 'doc_1', 'doc_2', 'doc_3',
                       'doc_4', 'doc_5', 'doc_6', 'doc_7'])
sim_scores = np.array([0.72, 0.45, 0.91, 0.38, 0.85, 0.61, 0.79, 0.55])

# Return top 3 doc_ids with their scores, highest first
# Expected: doc_2 (0.91), doc_4 (0.85), doc_6 (0.79)

#print(np.argsort(sim_scores)) #[3 1 7 5 0 6 4 2]

top3_idx = np.argsort(sim_scores)[::-1][:3] #[2 4 6]

print("Top 3 results:")
for idx in top3_idx:
    print(f"{doc_ids[idx]} — similarity: {sim_scores[idx]}")

[3 1 7 5 0 6 4 2]
Top 3 results:
doc_2 — similarity: 0.91
doc_4 — similarity: 0.85
doc_6 — similarity: 0.79


In [ ]:
# Matrix multiplication for batch similarity (Hard)
# Instead of computing cosine similarity one pair at a time, compute it for an entire batch using matrix multiplication. Given one query vector and 5 document vectors, compute all similarities at once.

np.random.seed(42)
query = np.random.randn(4)
docs  = np.random.randn(5, 4)

print(query)
print(docs)

# Step 1 — normalise query
query_norm = query / np.linalg.norm(query)

# Step 2 — normalise each doc row
doc_norms  = np.linalg.norm(docs, axis=1, keepdims=True)   # shape (5,1)
docs_norm  = docs / doc_norms                               # shape (5,4)

# Step 3 — batch cosine similarity via matrix multiply
# query_norm shape: (4,)  →  treat as (1,4)
# docs_norm.T shape: (4,5)
# result shape: (5,)
similarities = docs_norm @ query_norm   # equivalent to query_norm @ docs_norm.T

print(f"Similarities: {np.round(similarities, 4)}")
# e.g. [ 0.3801 -0.1234  0.5621  0.2198 -0.4012]

best_doc = np.argmax(similarities)
print(f"Most similar doc: index {best_doc} with score {similarities[best_doc]:.4f}")

[ 0.49671415 -0.1382643   0.64768854  1.52302986]
[[-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783 -0.56228753]
 [-1.01283112  0.31424733 -0.90802408 -1.4123037 ]
 [ 1.46564877 -0.2257763   0.0675282  -1.42474819]]
Similarities: [ 0.6805 -0.7813 -0.3462 -0.9544 -0.3833]
Most similar doc: index 0 with score 0.6805


In [ ]:
#Statistical summary of embedding space (Hard)
#Given a matrix of embeddings, compute a full statistical profile — mean vector (centroid), variance per dimension, and find which document is closest to the centroid.
import numpy as np

np.random.seed(7)
embeddings = np.random.randn(8, 6)   # 8 documents, 6-dim embeddings
print(embeddings)

# 14a. Centroid — mean vector across all documents (shape: 6,)
centroid = embeddings.mean(axis = 0)
print(f"Centroid: {np.round(centroid, 3)}")

# 14b. Variance per dimension (how spread out is each dimension?)
variance = embeddings.var(axis=0, ddof=1)
print(f"Variance: {np.round(variance, 3)}")

# 14c. Which document is closest to the centroid? (use Euclidean distance)
distances = np.linalg.norm(embeddings-centroid, axis = 1)
shorter_index = np.argmin(distances)
print(f"Distances to centroid: {np.round(distances, 4)}")
print(f"Document index closest to centroid is {shorter_index} and the document is: {np.round(embeddings[shorter_index],3)} ")
print(f"Closer document distance: {distances[shorter_index]:.3f}")
print("Shape:", distances.shape)

# 14d. Which dimension has the highest variance?
high_var_idx = np.argmax(variance)
print(f"High variance index is {high_var_idx} and the value is {np.round(variance[high_var_idx], 3)}")

[[ 1.69052570e+00 -4.65937371e-01  3.28201637e-02  4.07516283e-01
  -7.88923029e-01  2.06557291e-03]
 [-8.90385858e-04 -1.75472431e+00  1.01765801e+00  6.00498516e-01
  -6.25428974e-01 -1.71548261e-01]
 [ 5.05299374e-01 -2.61356415e-01 -2.42749079e-01 -1.45324141e+00
   5.54580312e-01  1.23880905e-01]
 [ 2.74459924e-01 -1.52652453e+00  1.65069969e+00  1.54335535e-01
  -3.87139943e-01  2.02907222e+00]
 [-4.53860299e-02 -1.45067870e+00 -4.05227855e-01 -2.28831510e+00
   1.04939655e+00 -4.16474319e-01]
 [-7.42553525e-01  1.07247013e+00 -1.65107559e+00  5.35429356e-01
  -2.06441480e+00 -6.62159340e-01]
 [-1.20421985e+00  1.46197563e+00  1.76616088e+00 -3.29413752e-01
   8.40733242e-01 -1.79986401e-01]
 [ 5.68061887e-01 -7.52837196e-01 -1.70833920e+00 -1.80309866e+00
   3.83121852e-01  2.24759505e+00]]
Centroid: [ 0.131 -0.46   0.057 -0.522 -0.13   0.372]
Variance: [0.768 1.423 1.817 1.338 1.079 1.25 ]
Distances to centroid: [1.967  2.1017 1.291  2.6397 2.5216 3.4582 3.1109 2.9697]
Document

In [1]:
# COMBINED CHALLENGE (Hard).
#Build embedding_stats(embeddings) that returns a full analysis dict:

# centroid — mean vector (shape: n_dims,)
# mean_pairwise_similarity — average cosine similarity between all pairs of documents
# most_similar_pair — tuple of indices (i, j) with highest cosine similarity
# least_similar_pair — tuple of indices (i, j) with lowest cosine similarity
# dim_variance — variance per dimension
# most_variable_dim — index of most variable dimension
import numpy as np

def embedding_stats(embeddings):

  variance = embeddings.var(axis= 0, ddof=1).round(4)

  norms = np.linalg.norm(embeddings, axis=1, keepdims=True)
  normed = embeddings / norms

  sim_matrix = normed @ normed.T
  np.fill_diagonal(sim_matrix, np.nan)

   # Most and least similar pairs
  flat_idx_max = np.nanargmax(sim_matrix)
  flat_idx_min = np.nanargmin(sim_matrix)
  i_max, j_max = np.unravel_index(flat_idx_max, sim_matrix.shape)
  i_min, j_min = np.unravel_index(flat_idx_min, sim_matrix.shape)

  return {
      'centroid' : embeddings.mean(axis=0).round(4),
      'mean_pairwise_similarity': round(float(np.nanmean(sim_matrix)),4),
      'most_similar_pair':  (int(i_max), int(j_max)),
      'least_similar_pair':   (int(i_min), int(j_min)),
      'dim_variance' : variance,
      'most_variable_dim': int(np.argmax(variance))

  }

np.random.seed(0)
embeddings = np.random.randn(6, 4)   # 6 docs, 4-dim

result = embedding_stats(embeddings)
print(result)
print(result['most_similar_pair'])    # e.g. (1, 4)
print(result['mean_pairwise_similarity'])  # e.g. -0.05

{'centroid': array([0.5384, 0.0673, 0.6157, 0.3802]), 'mean_pairwise_similarity': 0.1012, 'most_similar_pair': (0, 3), 'least_similar_pair': (1, 5), 'dim_variance': array([2.84  , 0.3482, 0.1298, 1.5367]), 'most_variable_dim': 0}
(0, 3)
0.1012
